//
// Created by Albert Teira on 24/11/2018.
//

#ifndef PROJECTEALGORISMIA_JACCARDSIMILARITYKSHINGLES_HH
#define PROJECTEALGORISMIA_JACCARDSIMILARITYKSHINGLES_HH


class JaccardSimilarityKShingles {

};


#endif //PROJECTEALGORISMIA_JACCARDSIMILARITYKSHINGLES_HH
